import type { Lead, Reminder } from "./types"

function daysAgo(days: number): string {
  const d = new Date()
  d.setDate(d.getDate() - days)
  return d.toISOString()
}

function hoursAgo(hours: number): string {
  const d = new Date()
  d.setHours(d.getHours() - hours)
  return d.toISOString()
}

function daysFromNow(days: number): string {
  const d = new Date()
  d.setDate(d.getDate() + days)
  return d.toISOString()
}

export const mockLeads: Lead[] = [
  // === COLD LEADS (steps 1-3 of 10) ===
  {
    id: "lead-001",
    name: "Dr. Carlos Mendoza",
    phone: "+52 55 1234 5678",
    company: "Hospital Central de Mexico",
    temperature: "cold",
    productCategory: "material_general",
    decisionTreeStep: 1,
    totalSteps: 10,
    createdAt: daysAgo(14),
    updatedAt: daysAgo(14),
    lastInteraction: daysAgo(14),
    status: "new",
    notes: [],
    reminders: [],
    conversation: [
      { id: "msg-001-1", content: "Bienvenido a DIART. Somos especialistas en insumos medicos. Seleccione el area de su interes:\n1. Material en General\n2. Medio de Contraste\n3. Equipo Medico\n4. Servicios Integrales", sender: "bot", timestamp: daysAgo(14), step: 1 },
      { id: "msg-001-2", content: "1", sender: "user", timestamp: daysAgo(14), step: 1 },
    ],
  },
  {
    id: "lead-002",
    name: "Lic. Maria Torres",
    phone: "+52 33 9876 5432",
    company: "Clinica Santa Fe",
    temperature: "cold",
    productCategory: "medio_contraste",
    decisionTreeStep: 2,
    totalSteps: 10,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(12),
    lastInteraction: daysAgo(12),
    status: "new",
    notes: [],
    reminders: [],
    conversation: [
      { id: "msg-002-1", content: "Bienvenido a DIART. Somos especialistas en insumos medicos. Seleccione el area de su interes:\n1. Material en General\n2. Medio de Contraste\n3. Equipo Medico\n4. Servicios Integrales", sender: "bot", timestamp: daysAgo(12), step: 1 },
      { id: "msg-002-2", content: "2", sender: "user", timestamp: daysAgo(12), step: 1 },
      { id: "msg-002-3", content: "Excelente. En Medio de Contraste manejamos las mejores marcas. Cual es su volumen de consumo mensual?\n1. Bajo (1-10 unidades)\n2. Medio (11-50 unidades)\n3. Alto (51+ unidades)", sender: "bot", timestamp: daysAgo(12), step: 2 },
      { id: "msg-002-4", content: "No estoy segura, dejeme consultar", sender: "user", timestamp: daysAgo(12), step: 2 },
    ],
  },
  {
    id: "lead-003",
    name: "Ing. Roberto Alvarez",
    phone: "+52 81 5555 1234",
    temperature: "cold",
    productCategory: "equipo_medico",
    decisionTreeStep: 2,
    totalSteps: 10,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(10),
    lastInteraction: daysAgo(10),
    status: "new",
    notes: [],
    reminders: [],
    conversation: [
      { id: "msg-003-1", content: "Bienvenido a DIART. Somos especialistas en insumos medicos. Seleccione el area de su interes:\n1. Material en General\n2. Medio de Contraste\n3. Equipo Medico\n4. Servicios Integrales", sender: "bot", timestamp: daysAgo(10), step: 1 },
      { id: "msg-003-2", content: "3", sender: "user", timestamp: daysAgo(10), step: 1 },
      { id: "msg-003-3", content: "Perfecto. En Equipo Medico ofrecemos soluciones de vanguardia. Que tipo de equipo necesita?\n1. Diagnostico por imagen\n2. Monitoreo de pacientes\n3. Equipo quirurgico\n4. Laboratorio clinico", sender: "bot", timestamp: daysAgo(10), step: 2 },
      { id: "msg-003-4", content: "Gracias, lo voy a pensar", sender: "user", timestamp: daysAgo(10), step: 2 },
    ],
  },
  {
    id: "lead-004",
    name: "Dra. Patricia Gomez",
    phone: "+52 222 3334 4456",
    company: "Laboratorios del Valle",
    temperature: "cold",
    productCategory: "servicios_integrales",
    decisionTreeStep: 3,
    totalSteps: 10,
    createdAt: daysAgo(8),
    updatedAt: daysAgo(8),
    lastInteraction: daysAgo(8),
    status: "new",
    notes: [],
    reminders: [],
    conversation: [
      { id: "msg-004-1", content: "Bienvenido a DIART. Somos especialistas en insumos medicos. Seleccione el area de su interes:\n1. Material en General\n2. Medio de Contraste\n3. Equipo Medico\n4. Servicios Integrales", sender: "bot", timestamp: daysAgo(8), step: 1 },
      { id: "msg-004-2", content: "4", sender: "user", timestamp: daysAgo(8), step: 1 },
      { id: "msg-004-3", content: "Nuestros Servicios Integrales incluyen soporte completo. Que tipo de servicio requiere?\n1. Mantenimiento de equipo\n2. Capacitacion de personal\n3. Consultoria tecnica\n4. Abastecimiento programado", sender: "bot", timestamp: daysAgo(8), step: 2 },
      { id: "msg-004-4", content: "1", sender: "user", timestamp: daysAgo(8), step: 2 },
      { id: "msg-004-5", content: "Para mantenimiento, necesitamos conocer su inventario actual. Podria proporcionarnos la marca y modelo de sus equipos principales?", sender: "bot", timestamp: daysAgo(8), step: 3 },
      { id: "msg-004-6", content: "Ahorita no tengo esa informacion a la mano", sender: "user", timestamp: daysAgo(8), step: 3 },
    ],
  },
  {
    id: "lead-005",
    name: "Dr. Fernando Ramirez",
    phone: "+52 664 7778 8890",
    temperature: "cold",
    productCategory: "material_general",
    decisionTreeStep: 1,
    totalSteps: 10,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
    lastInteraction: daysAgo(7),
    status: "new",
    notes: [],
    reminders: [],
    conversation: [
      { id: "msg-005-1", content: "Bienvenido a DIART. Somos especialistas en insumos medicos. Seleccione el area de su interes:\n1. Material en General\n2. Medio de Contraste\n3. Equipo Medico\n4. Servicios Integrales", sender: "bot", timestamp: daysAgo(7), step: 1 },
      { id: "msg-005-2", content: "Hola, solo estaba curioseando", sender: "user", timestamp: daysAgo(7), step: 1 },
    ],
  },

  // === WARM LEADS (steps 4-7 of 10) ===
  {
    id: "lead-006",
    name: "Dra. Ana Lucia Herrera",
    phone: "+52 55 9988 7766",
    company: "Hospital Angeles",
    temperature: "warm",
    productCategory: "medio_contraste",
    decisionTreeStep: 5,
    totalSteps: 10,
    createdAt: daysAgo(6),
    updatedAt: daysAgo(3),
    lastInteraction: daysAgo(3),
    status: "in_progress",
    notes: [
      { id: "note-006-1", content: "Interesada en medio de contraste para tomografia. Solicito catalogo de precios.", author: "Admin", createdAt: daysAgo(4) },
    ],
    reminders: [],
    conversation: [
      { id: "msg-006-1", content: "Bienvenido a DIART. Somos especialistas en insumos medicos. Seleccione el area de su interes:\n1. Material en General\n2. Medio de Contraste\n3. Equipo Medico\n4. Servicios Integrales", sender: "bot", timestamp: daysAgo(6), step: 1 },
      { id: "msg-006-2", content: "2", sender: "user", timestamp: daysAgo(6), step: 1 },
      { id: "msg-006-3", content: "Excelente. En Medio de Contraste manejamos las mejores marcas. Cual es su volumen de consumo mensual?\n1. Bajo (1-10 unidades)\n2. Medio (11-50 unidades)\n3. Alto (51+ unidades)", sender: "bot", timestamp: daysAgo(6), step: 2 },
      { id: "msg-006-4", content: "3", sender: "user", timestamp: daysAgo(6), step: 2 },
      { id: "msg-006-5", content: "Perfecto, alto volumen. Que tipo de medio de contraste utiliza actualmente?\n1. Yodado\n2. Gadolinio\n3. Bario\n4. Varios tipos", sender: "bot", timestamp: daysAgo(6), step: 3 },
      { id: "msg-006-6", content: "4", sender: "user", timestamp: daysAgo(6), step: 3 },
      { id: "msg-006-7", content: "Entendido, manejan varios tipos. Cuantos estudios de imagen realizan al mes en su institucion?\n1. Menos de 100\n2. 100 a 500\n3. Mas de 500", sender: "bot", timestamp: daysAgo(5), step: 4 },
      { id: "msg-006-8", content: "2", sender: "user", timestamp: daysAgo(5), step: 4 },
      { id: "msg-006-9", content: "Excelente volumen. Actualmente tienen contrato con algun proveedor de medio de contraste?\n1. Si, pero estamos buscando alternativas\n2. Si, estamos satisfechos pero queremos comparar\n3. No, necesitamos un proveedor", sender: "bot", timestamp: daysAgo(3), step: 5 },
      { id: "msg-006-10", content: "1, estamos buscando mejores precios", sender: "user", timestamp: daysAgo(3), step: 5 },
    ],
  },
  {
    id: "lead-007",
    name: "Lic. Jorge Villanueva",
    phone: "+52 33 1122 3344",
    company: "Clinica del Sol",
    temperature: "warm",
    productCategory: "equipo_medico",
    decisionTreeStep: 6,
    totalSteps: 10,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(2),
    lastInteraction: daysAgo(2),
    status: "in_progress",
    notes: [
      { id: "note-007-1", content: "Necesita equipo de monitoreo para UCI nueva. Presupuesto amplio.", author: "Admin", createdAt: daysAgo(3) },
    ],
    reminders: [],
    conversation: [
      { id: "msg-007-1", content: "Bienvenido a DIART. Somos especialistas en insumos medicos. Seleccione el area de su interes:\n1. Material en General\n2. Medio de Contraste\n3. Equipo Medico\n4. Servicios Integrales", sender: "bot", timestamp: daysAgo(5), step: 1 },
      { id: "msg-007-2", content: "3", sender: "user", timestamp: daysAgo(5), step: 1 },
      { id: "msg-007-3", content: "Perfecto. En Equipo Medico ofrecemos soluciones de vanguardia. Que tipo de equipo necesita?\n1. Diagnostico por imagen\n2. Monitoreo de pacientes\n3. Equipo quirurgico\n4. Laboratorio clinico", sender: "bot", timestamp: daysAgo(5), step: 2 },
      { id: "msg-007-4", content: "2", sender: "user", timestamp: daysAgo(5), step: 2 },
      { id: "msg-007-5", content: "Monitoreo de pacientes. Para que area necesita los equipos?\n1. UCI/Terapia Intensiva\n2. Urgencias\n3. Hospitalizacion general\n4. Quirofano", sender: "bot", timestamp: daysAgo(4), step: 3 },
      { id: "msg-007-6", content: "1", sender: "user", timestamp: daysAgo(4), step: 3 },
      { id: "msg-007-7", content: "UCI es un area critica. Cuantas camas tiene planeadas para la unidad?\n1. 5-10 camas\n2. 11-20 camas\n3. Mas de 20 camas", sender: "bot", timestamp: daysAgo(4), step: 4 },
      { id: "msg-007-8", content: "2", sender: "user", timestamp: daysAgo(4), step: 4 },
      { id: "msg-007-9", content: "11-20 camas. Ya tiene un presupuesto asignado para este proyecto?\n1. Si, ya esta aprobado\n2. En proceso de aprobacion\n3. Aun no, necesito cotizacion primero", sender: "bot", timestamp: daysAgo(3), step: 5 },
      { id: "msg-007-10", content: "1", sender: "user", timestamp: daysAgo(3), step: 5 },
      { id: "msg-007-11", content: "Perfecto, presupuesto aprobado. Que plazo tiene para la implementacion del equipo?\n1. Inmediato (1-2 meses)\n2. Corto plazo (3-6 meses)\n3. Mediano plazo (6-12 meses)", sender: "bot", timestamp: daysAgo(2), step: 6 },
      { id: "msg-007-12", content: "2, entre 3 y 6 meses", sender: "user", timestamp: daysAgo(2), step: 6 },
    ],
  },
  {
    id: "lead-008",
    name: "Dra. Sofia Castillo",
    phone: "+52 81 4455 6677",
    company: "Centro Medico Nacional",
    temperature: "warm",
    productCategory: "material_general",
    decisionTreeStep: 4,
    totalSteps: 10,
    createdAt: daysAgo(4),
    updatedAt: daysAgo(1),
    lastInteraction: daysAgo(1),
    status: "in_progress",
    notes: [],
    reminders: [],
    conversation: [
      { id: "msg-008-1", content: "Bienvenido a DIART. Somos especialistas en insumos medicos. Seleccione el area de su interes:\n1. Material en General\n2. Medio de Contraste\n3. Equipo Medico\n4. Servicios Integrales", sender: "bot", timestamp: daysAgo(4), step: 1 },
      { id: "msg-008-2", content: "1", sender: "user", timestamp: daysAgo(4), step: 1 },
      { id: "msg-008-3", content: "Material en General. Que tipo de material necesita?\n1. Material de curacion\n2. Material desechable\n3. Instrumental\n4. Varios", sender: "bot", timestamp: daysAgo(4), step: 2 },
      { id: "msg-008-4", content: "4", sender: "user", timestamp: daysAgo(4), step: 2 },
      { id: "msg-008-5", content: "Entendido, necesita varios tipos. Cual es el volumen aproximado de su pedido?\n1. Pequeno (menos de $50,000 MXN)\n2. Mediano ($50,000 - $200,000 MXN)\n3. Grande (mas de $200,000 MXN)", sender: "bot", timestamp: daysAgo(3), step: 3 },
      { id: "msg-008-6", content: "3", sender: "user", timestamp: daysAgo(3), step: 3 },
      { id: "msg-008-7", content: "Gran volumen. Con que frecuencia realiza sus pedidos?\n1. Semanal\n2. Quincenal\n3. Mensual\n4. Trimestral", sender: "bot", timestamp: daysAgo(1), step: 4 },
      { id: "msg-008-8", content: "2, cada 15 dias", sender: "user", timestamp: daysAgo(1), step: 4 },
    ],
  },
  {
    id: "lead-009",
    name: "Dr. Miguel Angel Reyes",
    phone: "+52 55 8877 6655",
    company: "Hospital Metropolitano",
    temperature: "warm",
    productCategory: "servicios_integrales",
    decisionTreeStep: 7,
    totalSteps: 10,
    createdAt: daysAgo(9),
    updatedAt: daysAgo(1),
    lastInteraction: daysAgo(1),
    status: "in_progress",
    notes: [
      { id: "note-009-1", content: "Muy interesado en el servicio de abastecimiento programado. Quiere una presentacion formal.", author: "Admin", createdAt: daysAgo(5) },
      { id: "note-009-2", content: "Se programo llamada de seguimiento para la proxima semana.", author: "Admin", createdAt: daysAgo(2) },
    ],
    reminders: [],
    conversation: [
      { id: "msg-009-1", content: "Bienvenido a DIART. Somos especialistas en insumos medicos. Seleccione el area de su interes:\n1. Material en General\n2. Medio de Contraste\n3. Equipo Medico\n4. Servicios Integrales", sender: "bot", timestamp: daysAgo(9), step: 1 },
      { id: "msg-009-2", content: "4", sender: "user", timestamp: daysAgo(9), step: 1 },
      { id: "msg-009-3", content: "Nuestros Servicios Integrales incluyen soporte completo. Que tipo de servicio requiere?\n1. Mantenimiento de equipo\n2. Capacitacion de personal\n3. Consultoria tecnica\n4. Abastecimiento programado", sender: "bot", timestamp: daysAgo(9), step: 2 },
      { id: "msg-009-4", content: "4", sender: "user", timestamp: daysAgo(9), step: 2 },
      { id: "msg-009-5", content: "Abastecimiento programado. Cuantas areas abastece su hospital?\n1. 1-5 areas\n2. 6-15 areas\n3. Mas de 15 areas", sender: "bot", timestamp: daysAgo(8), step: 3 },
      { id: "msg-009-6", content: "3", sender: "user", timestamp: daysAgo(8), step: 3 },
      { id: "msg-009-7", content: "Es un hospital grande. Actualmente cuentan con un sistema de gestion de inventarios?\n1. Si, automatizado\n2. Si, manual\n3. No", sender: "bot", timestamp: daysAgo(7), step: 4 },
      { id: "msg-009-8", content: "2, es manual y queremos mejorar", sender: "user", timestamp: daysAgo(7), step: 4 },
      { id: "msg-009-9", content: "Perfecto, podemos ayudar con eso. Cual es su presupuesto anual para insumos medicos?\n1. Menos de $1M MXN\n2. $1M - $5M MXN\n3. Mas de $5M MXN", sender: "bot", timestamp: daysAgo(5), step: 5 },
      { id: "msg-009-10", content: "3", sender: "user", timestamp: daysAgo(5), step: 5 },
      { id: "msg-009-11", content: "Excelente. Quienes participan en la toma de decision de compra?\n1. Solo yo\n2. Comite de compras\n3. Direccion general", sender: "bot", timestamp: daysAgo(3), step: 6 },
      { id: "msg-009-12", content: "2, el comite de compras", sender: "user", timestamp: daysAgo(3), step: 6 },
      { id: "msg-009-13", content: "Entendido. Podemos agendar una presentacion ante el comite. Necesitan una propuesta tecnica o comercial?\n1. Tecnica\n2. Comercial\n3. Ambas", sender: "bot", timestamp: daysAgo(1), step: 7 },
      { id: "msg-009-14", content: "3, ambas por favor", sender: "user", timestamp: daysAgo(1), step: 7 },
    ],
  },
  {
    id: "lead-010",
    name: "Lic. Andrea Navarro",
    phone: "+52 442 3344 5566",
    company: "Farmacia Especializada Plus",
    temperature: "warm",
    productCategory: "material_general",
    decisionTreeStep: 5,
    totalSteps: 10,
    createdAt: daysAgo(3),
    updatedAt: hoursAgo(12),
    lastInteraction: hoursAgo(12),
    status: "in_progress",
    notes: [],
    reminders: [],
    conversation: [
      { id: "msg-010-1", content: "Bienvenido a DIART. Somos especialistas en insumos medicos. Seleccione el area de su interes:\n1. Material en General\n2. Medio de Contraste\n3. Equipo Medico\n4. Servicios Integrales", sender: "bot", timestamp: daysAgo(3), step: 1 },
      { id: "msg-010-2", content: "1", sender: "user", timestamp: daysAgo(3), step: 1 },
      { id: "msg-010-3", content: "Material en General. Que tipo de material necesita?\n1. Material de curacion\n2. Material desechable\n3. Instrumental\n4. Varios", sender: "bot", timestamp: daysAgo(3), step: 2 },
      { id: "msg-010-4", content: "2", sender: "user", timestamp: daysAgo(3), step: 2 },
      { id: "msg-010-5", content: "Material desechable. Cuantos puntos de entrega tiene?\n1. Un solo punto\n2. 2-5 puntos\n3. Mas de 5 puntos", sender: "bot", timestamp: daysAgo(2), step: 3 },
      { id: "msg-010-6", content: "2", sender: "user", timestamp: daysAgo(2), step: 3 },
      { id: "msg-010-7", content: "2-5 puntos de entrega. Cual es su frecuencia de reabastecimiento?\n1. Semanal\n2. Quincenal\n3. Mensual", sender: "bot", timestamp: daysAgo(1), step: 4 },
      { id: "msg-010-8", content: "1", sender: "user", timestamp: daysAgo(1), step: 4 },
      { id: "msg-010-9", content: "Reabastecimiento semanal. Le interesaria un contrato de suministro a largo plazo con descuento por volumen?\n1. Si, me interesa\n2. Prefiero comprar por pedido\n3. Necesito mas informacion", sender: "bot", timestamp: hoursAgo(12), step: 5 },
      { id: "msg-010-10", content: "3, necesito saber los descuentos", sender: "user", timestamp: hoursAgo(12), step: 5 },
    ],
  },

  // === HOT LEADS (steps 8-10 of 10) ===
  {
    id: "lead-011",
    name: "Dr. Eduardo Vega",
    phone: "+52 55 1111 2222",
    company: "Hospital de Especialidades ISSTE",
    temperature: "hot",
    productCategory: "medio_contraste",
    decisionTreeStep: 9,
    totalSteps: 10,
    createdAt: daysAgo(11),
    updatedAt: hoursAgo(2),
    lastInteraction: hoursAgo(2),
    status: "in_progress",
    notes: [
      { id: "note-011-1", content: "Lead muy caliente. Ya tiene presupuesto aprobado y urgencia por desabasto.", author: "Admin", createdAt: daysAgo(5) },
      { id: "note-011-2", content: "Solicita entrega inmediata de 200 unidades de Iopamidol.", author: "Admin", createdAt: daysAgo(2) },
      { id: "note-011-3", content: "Se envio cotizacion formal. Esperando orden de compra.", author: "Admin", createdAt: hoursAgo(5) },
    ],
    reminders: [],
    conversation: [
      { id: "msg-011-1", content: "Bienvenido a DIART. Somos especialistas en insumos medicos. Seleccione el area de su interes:\n1. Material en General\n2. Medio de Contraste\n3. Equipo Medico\n4. Servicios Integrales", sender: "bot", timestamp: daysAgo(11), step: 1 },
      { id: "msg-011-2", content: "2, medio de contraste urgente", sender: "user", timestamp: daysAgo(11), step: 1 },
      { id: "msg-011-3", content: "Excelente. En Medio de Contraste manejamos las mejores marcas. Cual es su volumen de consumo mensual?\n1. Bajo (1-10 unidades)\n2. Medio (11-50 unidades)\n3. Alto (51+ unidades)", sender: "bot", timestamp: daysAgo(11), step: 2 },
      { id: "msg-011-4", content: "3, alto volumen", sender: "user", timestamp: daysAgo(11), step: 2 },
      { id: "msg-011-5", content: "Perfecto, alto volumen. Que tipo de medio de contraste utiliza actualmente?\n1. Yodado\n2. Gadolinio\n3. Bario\n4. Varios tipos", sender: "bot", timestamp: daysAgo(10), step: 3 },
      { id: "msg-011-6", content: "1, yodado para CT", sender: "user", timestamp: daysAgo(10), step: 3 },
      { id: "msg-011-7", content: "Cuantos estudios de imagen realizan al mes?\n1. Menos de 100\n2. 100 a 500\n3. Mas de 500", sender: "bot", timestamp: daysAgo(9), step: 4 },
      { id: "msg-011-8", content: "3", sender: "user", timestamp: daysAgo(9), step: 4 },
      { id: "msg-011-9", content: "Actualmente tienen contrato con algun proveedor?\n1. Si, pero estamos buscando alternativas\n2. Si, estamos satisfechos pero queremos comparar\n3. No, necesitamos un proveedor", sender: "bot", timestamp: daysAgo(8), step: 5 },
      { id: "msg-011-10", content: "3, nuestro proveedor anterior incumplio", sender: "user", timestamp: daysAgo(8), step: 5 },
      { id: "msg-011-11", content: "Entendemos la urgencia. Cual es su presupuesto para esta compra?\n1. Menos de $100K MXN\n2. $100K - $500K MXN\n3. Mas de $500K MXN", sender: "bot", timestamp: daysAgo(7), step: 6 },
      { id: "msg-011-12", content: "3", sender: "user", timestamp: daysAgo(7), step: 6 },
      { id: "msg-011-13", content: "Perfecto. Necesita factura para institucion publica?\n1. Si, con requisitos fiscales especificos\n2. No, factura regular", sender: "bot", timestamp: daysAgo(5), step: 7 },
      { id: "msg-011-14", content: "1", sender: "user", timestamp: daysAgo(5), step: 7 },
      { id: "msg-011-15", content: "Entendido. Nuestro equipo de ventas institucionales puede manejar esto. Cuando necesita la primera entrega?\n1. Esta semana\n2. Proxima semana\n3. En 2-4 semanas", sender: "bot", timestamp: daysAgo(3), step: 8 },
      { id: "msg-011-16", content: "1, es urgente", sender: "user", timestamp: daysAgo(3), step: 8 },
      { id: "msg-011-17", content: "Perfecto. Para formalizar, necesitamos:\n1. Ya tengo orden de compra lista\n2. Necesito generar la orden\n3. Necesito la cotizacion formal primero", sender: "bot", timestamp: hoursAgo(2), step: 9 },
      { id: "msg-011-18", content: "3, envienmela por favor", sender: "user", timestamp: hoursAgo(2), step: 9 },
    ],
  },
  {
    id: "lead-012",
    name: "Dra. Gabriela Orozco",
    phone: "+52 33 2233 4455",
    company: "Clinica de la Mujer",
    temperature: "hot",
    productCategory: "equipo_medico",
    decisionTreeStep: 8,
    totalSteps: 10,
    createdAt: daysAgo(13),
    updatedAt: hoursAgo(6),
    lastInteraction: hoursAgo(6),
    status: "in_progress",
    notes: [
      { id: "note-012-1", content: "Necesita ultrasonido de alta gama para su clinica. Presupuesto de $800K MXN.", author: "Admin", createdAt: daysAgo(7) },
      { id: "note-012-2", content: "Ya vio demo del equipo y le gusto. Falta aprobacion de su socio.", author: "Admin", createdAt: daysAgo(2) },
    ],
    reminders: [],
    conversation: [
      { id: "msg-012-1", content: "Bienvenido a DIART. Somos especialistas en insumos medicos. Seleccione el area de su interes:\n1. Material en General\n2. Medio de Contraste\n3. Equipo Medico\n4. Servicios Integrales", sender: "bot", timestamp: daysAgo(13), step: 1 },
      { id: "msg-012-2", content: "3", sender: "user", timestamp: daysAgo(13), step: 1 },
      { id: "msg-012-3", content: "Perfecto. Que tipo de equipo necesita?\n1. Diagnostico por imagen\n2. Monitoreo de pacientes\n3. Equipo quirurgico\n4. Laboratorio clinico", sender: "bot", timestamp: daysAgo(13), step: 2 },
      { id: "msg-012-4", content: "1", sender: "user", timestamp: daysAgo(13), step: 2 },
      { id: "msg-012-5", content: "Diagnostico por imagen. Que modalidad?\n1. Ultrasonido\n2. Rayos X\n3. Tomografia\n4. Resonancia", sender: "bot", timestamp: daysAgo(12), step: 3 },
      { id: "msg-012-6", content: "1, ultrasonido de alta gama", sender: "user", timestamp: daysAgo(12), step: 3 },
      { id: "msg-012-7", content: "Ultrasonido de alta gama. Para que especialidad?\n1. Ginecologia/Obstetricia\n2. Cardiologia\n3. Medicina general\n4. Musculoesqueletico", sender: "bot", timestamp: daysAgo(11), step: 4 },
      { id: "msg-012-8", content: "1", sender: "user", timestamp: daysAgo(11), step: 4 },
      { id: "msg-012-9", content: "Excelente. Tiene presupuesto definido?\n1. Si, ya esta aprobado\n2. En proceso\n3. Necesito cotizacion", sender: "bot", timestamp: daysAgo(9), step: 5 },
      { id: "msg-012-10", content: "1, $800K MXN", sender: "user", timestamp: daysAgo(9), step: 5 },
      { id: "msg-012-11", content: "Con ese presupuesto tenemos opciones excelentes. Le interesa agendar una demostracion?\n1. Si, en mi clinica\n2. Si, en su showroom\n3. Prefiero ver especificaciones primero", sender: "bot", timestamp: daysAgo(7), step: 6 },
      { id: "msg-012-12", content: "2", sender: "user", timestamp: daysAgo(7), step: 6 },
      { id: "msg-012-13", content: "Agendamos la demo. Necesita financiamiento o sera pago directo?\n1. Financiamiento\n2. Pago directo\n3. Arrendamiento", sender: "bot", timestamp: daysAgo(4), step: 7 },
      { id: "msg-012-14", content: "2, pago directo", sender: "user", timestamp: daysAgo(4), step: 7 },
      { id: "msg-012-15", content: "Perfecto. Ya asistio a la demo y quedo satisfecha. Cuando le gustaria recibir el equipo?\n1. Lo antes posible\n2. En 2-4 semanas\n3. En 1-2 meses", sender: "bot", timestamp: hoursAgo(6), step: 8 },
      { id: "msg-012-16", content: "2, en unas semanas despues de confirmar con mi socio", sender: "user", timestamp: hoursAgo(6), step: 8 },
    ],
  },
  {
    id: "lead-013",
    name: "Dr. Alejandro Fuentes",
    phone: "+52 81 6677 8899",
    company: "Hospital San Jose",
    temperature: "hot",
    productCategory: "servicios_integrales",
    decisionTreeStep: 10,
    totalSteps: 10,
    createdAt: daysAgo(15),
    updatedAt: hoursAgo(1),
    lastInteraction: hoursAgo(1),
    status: "in_progress",
    notes: [
      { id: "note-013-1", content: "Lead completamente caliente. Quiere contratar servicio integral anual.", author: "Admin", createdAt: daysAgo(7) },
      { id: "note-013-2", content: "Comite de compras aprobo. Solo falta firma del director.", author: "Admin", createdAt: daysAgo(1) },
    ],
    reminders: [],
    conversation: [
      { id: "msg-013-1", content: "Bienvenido a DIART. Somos especialistas en insumos medicos. Seleccione el area de su interes:\n1. Material en General\n2. Medio de Contraste\n3. Equipo Medico\n4. Servicios Integrales", sender: "bot", timestamp: daysAgo(15), step: 1 },
      { id: "msg-013-2", content: "4", sender: "user", timestamp: daysAgo(15), step: 1 },
      { id: "msg-013-3", content: "Servicios Integrales. Que tipo de servicio requiere?\n1. Mantenimiento\n2. Capacitacion\n3. Consultoria\n4. Abastecimiento programado", sender: "bot", timestamp: daysAgo(15), step: 2 },
      { id: "msg-013-4", content: "4", sender: "user", timestamp: daysAgo(15), step: 2 },
      { id: "msg-013-5", content: "Abastecimiento programado. Cuantas areas?\n1. 1-5\n2. 6-15\n3. Mas de 15", sender: "bot", timestamp: daysAgo(14), step: 3 },
      { id: "msg-013-6", content: "3, tenemos 22 areas", sender: "user", timestamp: daysAgo(14), step: 3 },
      { id: "msg-013-7", content: "Hospital grande. Sistema de inventarios?\n1. Automatizado\n2. Manual\n3. No tienen", sender: "bot", timestamp: daysAgo(13), step: 4 },
      { id: "msg-013-8", content: "2", sender: "user", timestamp: daysAgo(13), step: 4 },
      { id: "msg-013-9", content: "Presupuesto anual para insumos?\n1. Menos de $1M\n2. $1M-$5M\n3. Mas de $5M", sender: "bot", timestamp: daysAgo(12), step: 5 },
      { id: "msg-013-10", content: "3, alrededor de $8M", sender: "user", timestamp: daysAgo(12), step: 5 },
      { id: "msg-013-11", content: "Decision de compra?\n1. Solo yo\n2. Comite\n3. Direccion", sender: "bot", timestamp: daysAgo(10), step: 6 },
      { id: "msg-013-12", content: "2", sender: "user", timestamp: daysAgo(10), step: 6 },
      { id: "msg-013-13", content: "Propuesta?\n1. Tecnica\n2. Comercial\n3. Ambas", sender: "bot", timestamp: daysAgo(8), step: 7 },
      { id: "msg-013-14", content: "3", sender: "user", timestamp: daysAgo(8), step: 7 },
      { id: "msg-013-15", content: "Ya revisaron la propuesta el comite?\n1. Si, aprobada\n2. En revision\n3. Necesitan presentacion", sender: "bot", timestamp: daysAgo(4), step: 8 },
      { id: "msg-013-16", content: "1, aprobada", sender: "user", timestamp: daysAgo(4), step: 8 },
      { id: "msg-013-17", content: "Excelente. Tipo de contrato?\n1. Anual\n2. Bianual\n3. Por proyecto", sender: "bot", timestamp: daysAgo(2), step: 9 },
      { id: "msg-013-18", content: "1, anual con posibilidad de renovar", sender: "user", timestamp: daysAgo(2), step: 9 },
      { id: "msg-013-19", content: "Perfecto. Para finalizar necesitamos:\n1. Ya tengo los documentos listos\n2. Necesito la plantilla de contrato\n3. Agendar reunion de firma", sender: "bot", timestamp: hoursAgo(1), step: 10 },
      { id: "msg-013-20", content: "3, agendemos la firma con el director", sender: "user", timestamp: hoursAgo(1), step: 10 },
    ],
  },
  {
    id: "lead-014",
    name: "Lic. Veronica Solis",
    phone: "+52 55 3344 5566",
    company: "Distribuidora Medica del Norte",
    temperature: "hot",
    productCategory: "material_general",
    decisionTreeStep: 8,
    totalSteps: 10,
    createdAt: daysAgo(6),
    updatedAt: hoursAgo(4),
    lastInteraction: hoursAgo(4),
    status: "in_progress",
    notes: [
      { id: "note-014-1", content: "Quiere contrato de distribucion mayorista. Volumen muy alto.", author: "Admin", createdAt: daysAgo(3) },
    ],
    reminders: [],
    conversation: [
      { id: "msg-014-1", content: "Bienvenido a DIART. Somos especialistas en insumos medicos. Seleccione el area de su interes:\n1. Material en General\n2. Medio de Contraste\n3. Equipo Medico\n4. Servicios Integrales", sender: "bot", timestamp: daysAgo(6), step: 1 },
      { id: "msg-014-2", content: "1", sender: "user", timestamp: daysAgo(6), step: 1 },
      { id: "msg-014-3", content: "Material en General. Que tipo?\n1. Curacion\n2. Desechable\n3. Instrumental\n4. Varios", sender: "bot", timestamp: daysAgo(6), step: 2 },
      { id: "msg-014-4", content: "4, todo tipo de material", sender: "user", timestamp: daysAgo(6), step: 2 },
      { id: "msg-014-5", content: "Volumen aproximado?\n1. Menos de $50K\n2. $50K-$200K\n3. Mas de $200K", sender: "bot", timestamp: daysAgo(5), step: 3 },
      { id: "msg-014-6", content: "3, somos distribuidora", sender: "user", timestamp: daysAgo(5), step: 3 },
      { id: "msg-014-7", content: "Frecuencia de pedidos?\n1. Semanal\n2. Quincenal\n3. Mensual\n4. Trimestral", sender: "bot", timestamp: daysAgo(4), step: 4 },
      { id: "msg-014-8", content: "1", sender: "user", timestamp: daysAgo(4), step: 4 },
      { id: "msg-014-9", content: "Contrato a largo plazo?\n1. Si\n2. Por pedido\n3. Mas informacion", sender: "bot", timestamp: daysAgo(4), step: 5 },
      { id: "msg-014-10", content: "1, nos interesa mucho", sender: "user", timestamp: daysAgo(4), step: 5 },
      { id: "msg-014-11", content: "Zona de cobertura?\n1. Local\n2. Regional\n3. Nacional", sender: "bot", timestamp: daysAgo(3), step: 6 },
      { id: "msg-014-12", content: "3, nacional", sender: "user", timestamp: daysAgo(3), step: 6 },
      { id: "msg-014-13", content: "Necesita credito o pago de contado?\n1. Credito a 30 dias\n2. Credito a 60 dias\n3. Contado\n4. Negociar", sender: "bot", timestamp: daysAgo(2), step: 7 },
      { id: "msg-014-14", content: "1", sender: "user", timestamp: daysAgo(2), step: 7 },
      { id: "msg-014-15", content: "Perfecto. Podemos agendar reunion para cerrar terminos?\n1. Si, esta semana\n2. Proxima semana\n3. Envien propuesta por correo", sender: "bot", timestamp: hoursAgo(4), step: 8 },
      { id: "msg-014-16", content: "1, lo antes posible", sender: "user", timestamp: hoursAgo(4), step: 8 },
    ],
  },
  {
    id: "lead-015",
    name: "Dr. Ricardo Morales",
    phone: "+52 222 7788 9900",
    company: "Sanatorio San Rafael",
    temperature: "hot",
    productCategory: "medio_contraste",
    decisionTreeStep: 9,
    totalSteps: 10,
    createdAt: daysAgo(8),
    updatedAt: hoursAgo(3),
    lastInteraction: hoursAgo(3),
    status: "in_progress",
    notes: [
      { id: "note-015-1", content: "Necesita Gadolinio para RM. Urge porque su proveedor le fallo.", author: "Admin", createdAt: daysAgo(4) },
      { id: "note-015-2", content: "Ya tiene la orden de compra generada.", author: "Admin", createdAt: hoursAgo(8) },
    ],
    reminders: [],
    conversation: [
      { id: "msg-015-1", content: "Bienvenido a DIART. Somos especialistas en insumos medicos. Seleccione el area de su interes:\n1. Material en General\n2. Medio de Contraste\n3. Equipo Medico\n4. Servicios Integrales", sender: "bot", timestamp: daysAgo(8), step: 1 },
      { id: "msg-015-2", content: "2", sender: "user", timestamp: daysAgo(8), step: 1 },
      { id: "msg-015-3", content: "Volumen de consumo?\n1. Bajo\n2. Medio\n3. Alto", sender: "bot", timestamp: daysAgo(8), step: 2 },
      { id: "msg-015-4", content: "2", sender: "user", timestamp: daysAgo(8), step: 2 },
      { id: "msg-015-5", content: "Tipo de medio de contraste?\n1. Yodado\n2. Gadolinio\n3. Bario\n4. Varios", sender: "bot", timestamp: daysAgo(7), step: 3 },
      { id: "msg-015-6", content: "2, Gadolinio para resonancia", sender: "user", timestamp: daysAgo(7), step: 3 },
      { id: "msg-015-7", content: "Estudios al mes?\n1. Menos de 100\n2. 100-500\n3. Mas de 500", sender: "bot", timestamp: daysAgo(6), step: 4 },
      { id: "msg-015-8", content: "1, alrededor de 80", sender: "user", timestamp: daysAgo(6), step: 4 },
      { id: "msg-015-9", content: "Proveedor actual?\n1. Buscando alternativa\n2. Comparando\n3. Necesitamos uno", sender: "bot", timestamp: daysAgo(5), step: 5 },
      { id: "msg-015-10", content: "3, nos fallo el anterior", sender: "user", timestamp: daysAgo(5), step: 5 },
      { id: "msg-015-11", content: "Presupuesto?\n1. Menos de $100K\n2. $100K-$500K\n3. Mas de $500K", sender: "bot", timestamp: daysAgo(4), step: 6 },
      { id: "msg-015-12", content: "2", sender: "user", timestamp: daysAgo(4), step: 6 },
      { id: "msg-015-13", content: "Factura especial?\n1. Si, institucion publica\n2. No, regular", sender: "bot", timestamp: daysAgo(3), step: 7 },
      { id: "msg-015-14", content: "2", sender: "user", timestamp: daysAgo(3), step: 7 },
      { id: "msg-015-15", content: "Cuando necesita entrega?\n1. Esta semana\n2. Proxima semana\n3. 2-4 semanas", sender: "bot", timestamp: daysAgo(1), step: 8 },
      { id: "msg-015-16", content: "1", sender: "user", timestamp: daysAgo(1), step: 8 },
      { id: "msg-015-17", content: "Para formalizar:\n1. Orden de compra lista\n2. Necesito generar orden\n3. Cotizacion primero", sender: "bot", timestamp: hoursAgo(3), step: 9 },
      { id: "msg-015-18", content: "1, ya la tengo lista", sender: "user", timestamp: hoursAgo(3), step: 9 },
    ],
  },
]

// Generate standalone reminders from leads
export const mockReminders: Reminder[] = [
  {
    id: "rem-001",
    leadId: "lead-006",
    leadName: "Dra. Ana Lucia Herrera",
    title: "Enviar catalogo de precios de medio de contraste",
    description: "Solicito catalogo actualizado con precios para alto volumen",
    dueDate: daysFromNow(1),
    completed: false,
    createdAt: daysAgo(3),
  },
  {
    id: "rem-002",
    leadId: "lead-007",
    leadName: "Lic. Jorge Villanueva",
    title: "Preparar cotizacion de monitores UCI",
    description: "11-20 camas, presupuesto aprobado, plazo 3-6 meses",
    dueDate: daysFromNow(2),
    completed: false,
    createdAt: daysAgo(2),
  },
  {
    id: "rem-003",
    leadId: "lead-011",
    leadName: "Dr. Eduardo Vega",
    title: "Seguimiento a cotizacion formal enviada",
    description: "Esperando orden de compra para 200 unidades de Iopamidol",
    dueDate: daysFromNow(0),
    completed: false,
    createdAt: hoursAgo(5),
  },
  {
    id: "rem-004",
    leadId: "lead-012",
    leadName: "Dra. Gabriela Orozco",
    title: "Llamar para confirmar decision con socio",
    description: "Ultrasonido de alta gama, $800K, esperando aprobacion del socio",
    dueDate: daysFromNow(3),
    completed: false,
    createdAt: daysAgo(1),
  },
  {
    id: "rem-005",
    leadId: "lead-013",
    leadName: "Dr. Alejandro Fuentes",
    title: "Agendar reunion de firma de contrato",
    description: "Contrato anual de abastecimiento, $8M. Falta firma del director.",
    dueDate: daysFromNow(1),
    completed: false,
    createdAt: hoursAgo(1),
  },
  {
    id: "rem-006",
    leadId: "lead-014",
    leadName: "Lic. Veronica Solis",
    title: "Reunion para cerrar terminos de distribucion",
    description: "Contrato nacional de distribucion mayorista, credito 30 dias",
    dueDate: daysFromNow(0),
    completed: false,
    createdAt: hoursAgo(4),
  },
  {
    id: "rem-007",
    leadId: "lead-015",
    leadName: "Dr. Ricardo Morales",
    title: "Procesar orden de compra de Gadolinio",
    description: "Ya tiene orden lista, necesita entrega esta semana",
    dueDate: daysFromNow(-1),
    completed: false,
    createdAt: hoursAgo(3),
  },
  {
    id: "rem-008",
    leadId: "lead-009",
    leadName: "Dr. Miguel Angel Reyes",
    title: "Enviar propuesta tecnica y comercial",
    dueDate: daysAgo(1),
    completed: true,
    createdAt: daysAgo(3),
  },
  {
    id: "rem-009",
    leadId: "lead-002",
    leadName: "Lic. Maria Torres",
    title: "Seguimiento por falta de informacion",
    description: "No sabia su volumen de consumo, darle seguimiento",
    dueDate: daysAgo(5),
    completed: true,
    createdAt: daysAgo(10),
  },
]
